name: Päivitä Finlex-data

on:
  schedule:
    - cron: '0 0 * * *'  # Ajetaan kerran päivässä klo 00:00 UTC (02:00 Suomen aikaa)
  push:
    branches:
      - main  # Käynnistyy myös, kun muutoksia pusketaan

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Hae viimeisin repositorio
        uses: actions/checkout@v3

      - name: Asenna Python ja riippuvuudet
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests xmltodict

      - name: Hae Finlex-data ja muunna JSON-muotoon
        run: python3 fetch_finlex.py

      - name: Commit ja push, jos tiedot muuttuivat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add finlex_data.json
          git commit -m "Päivitetty Finlex-data $(date +'%Y-%m-%d')" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/mikariihimaa/lainsaadanto-puu.git main

